### ISSUE TITLE
bag_to_raw seems to produce no output

### ISSUE THREAD

**Issue by AndreasAZiegler** [berndpfrommer/event_array_tools#2]
After having run `ros2 run event_array_tools bag_to_raw -t /event_camera/events -b events_2022-11-08-19-10-55/ -o test.raw -c evk4` on a recorded bag (which does contain data and can be played with `ros2 bag play`), I get an empty `.raw` file (only containing the header).
I had a quick look at the code and I'm a bit puzzled about `if (m.seq >= 45547) {` on [line 95](
https://github.com/berndpfrommer/event_array_tools/blob/master/src/bag_to_raw_ros2.cpp#L95). To my understanding, the output is only written if `m.seq >= 45547`. Is this intended (and I don't understand the logic, which is very likely) or a bug?

**Comment by berndpfrommer** [comment]
Thanks much for finding this embarrassing bug. Left-over debugging code! I just pushed a fix.

**Comment by AndreasAZiegler** [comment]
Thanks a lot for your work and the fast response.
